labs14-stampd/frontend

netlify.toml

created netlify.toml file with build and redierects

---

netlify.toml

Reverts labs14-stampd/frontend#7

Revert "created netlify.toml file with build and redierects"

---

netlify.toml

took away spaces on line 9 of toml file

---

client/package.json
client/src/App.jsx
client/src/components/Footer.jsx
client/src/components/Layout.jsx
client/src/components/NavBar.jsx
client/src/index.js
client/src/store/reducers/globalReducer.js
client/yarn.lock

Adds skeletal layout with the conflux library and using styled components.

adds nav, footer, conflux, and styled components

---

client/src/components/styles/Global.js
client/src/components/styles/Reset.js
client/src/components/styles/index.js
client/src/components/styles/themes.js

Style framework

---

client/src/App.jsx
client/src/Auth/PrivateRoute.js
client/src/views/Layout.jsx

made file for private route

---

client/package.json
client/src/App.jsx
client/src/Auth/PrivateRoute.js
client/src/components/NewSchoolForm.jsx
client/src/components/OnBoarding.jsx/NewSchoolForm.jsx
client/src/components/OnBoarding.jsx/OnBoardQueries.js
client/src/store/reducers/globalReducer.js
client/src/views/Dashboard.js
client/yarn.lock

new school form, school details form, tested on local .

New school form

---

client/package.json
client/src/Auth/auth-queries.js
client/src/Auth/auth0-wrapper.jsx
client/src/index.js
client/src/store/reducers/globalReducer.js
client/yarn.lock

Describe change or new feature here.

connects front end apollo to backend graphql

---

client/src/App.jsx
client/src/auth/authQueries.js
client/src/auth/authWrapper.jsx
client/src/clientQuery.js
client/src/components/dashboard/Dashboard.jsx
client/src/components/dashboard/onboarding/Onboard.jsx
client/src/components/dashboard/onboarding/SchoolDetailsForm.jsx

Changes object properties to add authToken for the backend for jwt intergration

Jwt integration

---

client/src/auth/authWrapper.jsx

Fixes bug for a work around to consent_required

changes payload authtoken value to sub

---

client/package.json
client/src/auth/authQueries.js
client/src/auth/authWrapper.jsx
client/src/components/Dashboard/CredentialsForm/index.jsx
client/src/components/Dashboard/CredentialsForm/queries.js
client/src/components/Dashboard/Onboard/SchoolDetailsForm.jsx
client/src/components/Field.jsx
client/yarn.lock

Adds a reusable styled component called `Field.jsx` that serves as a base for label-input field pairs.

Added styled component for label-input field pairs

---

client/package.json
client/src/auth/authQueries.js
client/src/auth/authWrapper.jsx
client/yarn.lock

tokenizes user object to be send down to backend server

Tokenize user object

---

client/src/App.jsx
client/src/components/Dashboard/CredentialsForm/index.jsx
client/src/components/Dashboard/CredentialsForm/queries.js
client/src/components/Dashboard/index.jsx

Describe change or new feature here.

adds button to check creds

---

client/package.json
client/src/auth/authWrapper.jsx
client/src/components/Dashboard/CredentialsForm/index.jsx
client/src/components/Dashboard/Onboard/SchoolDetailsForm.jsx
client/src/styles/Global.js
client/src/styles/Reset.js
client/src/styles/index.js

Fixes for linting errors and modification of linting script commands.

Fixes for linting errors

---

client/src/App.jsx
client/src/components/ErrorPage/index.jsx

Adds a 404 error page along with the corresponding routing.

404 error page & routing

---

client/src/components/Layout/NavBar.jsx

Clears local storage on the browser upon logging out.

Clear localStorage on logout

---

client/src/components/Dashboard/CredentialsForm/queries.js

Fixes a bug on FE, needed credName and ownerName for credentials

Added credName and ownerName to FE queries

---

client/package.json
client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
client/src/store/reducers/schoolReducer.js
client/yarn.lock

Implement full search functionality for search bar and update with styles/components for loading/displaying search state.

Implement Fuzzy Search and Associated Styling

---

client/src/components/Dashboard/Card/CredCardDeleteBtn.jsx

Add toast message on successful delete

add toast message to delete functionality

---

client/src/App.jsx
client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
client/src/components/Layout/MenuLayer.jsx
client/src/components/Layout/NavBar.jsx
client/src/components/Layout/index.jsx
client/src/styles/themes.js

Implement routing and functionality on the navbar menu tray

Implement Routing and Functionality on the Navbar Menu Tray

---

client/src/components/Dashboard/CredentialsForm/index.jsx

Add date input to replace default input in this format: `M/D/YYY` as a string.

add working date input

---

client/src/components/Dashboard/Card/CredCardDeleteBtn.jsx
client/src/components/Dashboard/CredentialsForm/index.jsx
client/src/components/Dashboard/Onboard/SchoolDetailsForm.jsx

- Add date input for the expiration date
- Remove spacing eslint violation
- Add toast to add school details on success 
- Change auto close rule on toast to false for delete and add school details

Misc fixes

---

client/src/components/Dashboard/DashboardLoading/StyledPlaceHolderBox/index.jsx
client/src/components/Dashboard/DashboardLoading/index.jsx
client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx

Add and style Dashboard placeholder when data fetch is at START state.

Dashboardloading

---

client/src/components/Dashboard/CredentialsForm/index.jsx
client/src/components/Dashboard/CredentialsForm/queries.js
client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
client/src/components/Dashboard/SchoolDashboard/index.jsx
client/src/index.js
client/src/store/reducers/schoolReducer.js

Fixes dashboard refresh bug

---

client/src/components/Dashboard/SchoolDashboard/MainDashboard.jsx
client/src/components/Dashboard/SchoolDashboard/index.jsx

Fix left/right credential card hover bug

Fix Left/Right Cred Card Hover Bug

---

client/src/components/Dashboard/Dashboard/index.jsx
client/src/components/Settings/StudentSettings/DetailsSettings.jsx
client/src/components/Settings/StudentSettings/EmailContainer.jsx
client/src/components/Settings/StudentSettings/StudentSettings.jsx
client/src/components/Settings/index.jsx
client/src/store/constants.js

Removed unneeded printed id from the email card and removed unneeded imports. Took setting option out of the school side for now. Cleaned up console warnings.

Cleaned up settings code

---

client/src/App.jsx
client/src/components/Dashboard/Dashboard/StudentDashboard.jsx
client/src/components/Dashboard/Dashboard/index.jsx
client/src/store/reducers/schoolReducer.js

Make bug fixes for rendering the dashboard data

Make bug fixes for rendering the dashboard data

---

client/src/components/Dashboard/Dashboard/SchoolDashboard.jsx
client/src/components/Settings/StudentSettings/EmailSettings.jsx

Infinitescroll

---

client/src/__testHelpers__/renderWithRouter/renderWithRouterAndProviders.jsx
client/src/__testHelpers__/rendererWithRouter/rendererWithRouterAndProviders.jsx
client/src/__tests__/Dashboard.test.js
client/src/__tests__/ErrorPage.test.js
client/src/__tests__/Footer.test.js
client/src/__tests__/Landing.test.js
client/src/__tests__/Layout.test.js
client/src/__tests__/Loading.test.js
client/src/__tests__/MenuLayer.test.js
client/src/__tests__/NavBar.test.js
client/src/__tests__/SchoolDashboard.test.js
client/src/__tests__/StudentDashboard.test.js
client/src/__tests__/__snapshots__/CredCard.test.js.snap
client/src/__tests__/__snapshots__/Dashboard.test.js.snap
client/src/__tests__/__snapshots__/ErrorPage.test.js.snap
client/src/__tests__/__snapshots__/Footer.test.js.snap
client/src/__tests__/__snapshots__/Landing.test.js.snap
client/src/__tests__/__snapshots__/Layout.test.js.snap
client/src/__tests__/__snapshots__/Loading.test.js.snap
client/src/__tests__/__snapshots__/NavBar.test.js.snap
client/src/__tests__/__snapshots__/SchoolDashboard.test.js.snap
client/src/__tests__/__snapshots__/StudentDashboard.test.js.snap
client/src/auth/__mocks__/authWrapper.jsx
client/src/components/Layout/Loading.jsx
client/src/components/Layout/NavBar.jsx
client/src/store/reducers/__mocks__/globalReducer.js
client/src/store/reducers/__mocks__/schoolReducer.js
client/src/store/reducers/__mocks__/studentReducer.js
client/src/store/reducers/schoolReducer.js

Update client `master` branch repository with additional testing suites

Add Additional Tests to Client

---

client/src/components/Settings/StudentSettings/EmailContainer.jsx
client/src/components/Settings/StudentSettings/EmailSettings.jsx
client/src/components/Settings/queries.js
client/src/store/reducers/studentReducer.js

Finish bug fixes for addEmail and removeEmail queries and mutations. It's synced with front-end client as well.

Finish Updates for bug/addEmail Branch

---

client/src/auth/authQueries.js
client/src/auth/authWrapper.jsx
client/src/clientQuery.js

Adds auth header token to auth headers.

Auth headers token

---

client/src/components/Dashboard/CredentialsForm/index.jsx

Change toast time to five seconds and dismiss the submitting toast when the submission is successful.

fix toast interval

---

client/src/components/Settings/queries.js

Removes userId from emailList query

Removed userId from emailList query

---

client/src/components/Settings/StudentSettings/EmailSettings.jsx

Describe change or new feature here.

Update email settings page to fix addEmail bug

---

client/public/index.html

Add new header tags to `index.html`

Add new header tags to index.html

---

client/src/images/stampdbackground.svg

update svg background in landing

---

client/public/index.html
client/src/components/Landing/index.jsx
client/src/components/Layout/NavBar.jsx
node_modules/.yarn-integrity

Describe change or new feature here.

Fixing logo
